### ISSUE TITLE
Problème démmarage PDF4Teachers-Windows-1.2.0.msi

### ISSUE THREAD

**Issue by michelwend** [ClementGre/PDF4Teachers#36]
Bonjour,
Je viens de faire l'installation. Puis je sélectionne le raccourci sur le bureau mais rien ne se passe. Pourriez-vous m'aider? En vous remerciant.

**Comment by ClementGre** [comment]
Bonjour, 

votre raccourcis du bureau est peut-être devenu obsolète avec un changement de version par exemple. Essayez de lancer l'application depuis la liste des applications du menu démarrer.

Sinon, la meilleur manière de savoir si le .exe fonctionne bien est de l'ouvrir dans un terminal, pour cela, ouvrez le terminal windows avec ``Windows+R`` puis tapez ``cmd`` puis ``Entrée``. Vous pouvez ensuite faire clic droit sur le raccourcis du bureau, puis copiez le texte affiché dans ``Cible :``. Vous devriez avoir quelque chose de cette forme : ``"C:\Program Files\PDF4Teachers\PDF4Teachers.exe"``. Vous devez ensuite coller ce texte dans le terminal windows, avec ``Ctrl+V``. Vous pouvez ensuite m'envoyer ce qu'affiche le terminal.

Si le terminal n'affiche rien, vous pouvez exécuter le fichier .bat de PDF4Teachers pour avoir plus d'informations, pour cela, collez le texte copié précédemment dans l'explorateur de fichiers (le champ du chemin du dossier courant). Faites ensuite ``Entrée`` et rendez vous dans le dossier ``runtime`` puis ``bin``. Vous pourrez ensuite exécuter le fichier ``PDF4Teachers.bat``

J'espère vous avoir aidé à résoudre votre problème.
\- Clément G.

**Comment by michelwend** [comment]
Bonjour,
J'avais effectivement effectué ces manipulations.
Voici le code erreur:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.awt.AWTError: Assistive Technology not found: com.sun.java.accessibility.AccessBridge
        at java.desktop/java.awt.Toolkit.newAWTError(Unknown Source)
        at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Unknown Source)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
        at java.desktop/java.awt.Desktop.isDesktopSupported(Unknown Source)
        at fr.themsou/fr.themsou.main.Main.<clinit>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: com.sun.java.accessibility.AccessBridge
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        ... 25 more
```
Auriez-vous une solution?

**Comment by ClementGre** [comment]
Bonjour,
ceci est en effet un problème de PDF4Teachers.
je ne peut pas reproduire le problème car cela dépend de la configuration de votre machine.
Je vous ai recompilé l'application avec quelques changements affin d'essayer de résoudre ce problème.
Vous pouvez désinstaller votre PDF4Teachers et installer [celui ci](https://tntgun.fr/img/api/drop/PDF4Teachers-1.2.0.zip) 
Si vous n'arrivez toujours pas à lancer l'application, refaites le protocole envoyé précédemment pour m'envoyer le message d'erreur.

Cordialement, Clément G.

**Comment by michelwend** [comment]
Bonjour,
Merci pour votre réactivité, cela fonctionne.
Bien cordialement
mw
