### ISSUE TITLE
Fails to run after build, with translation resources issue

### ISSUE THREAD

**Issue by olberger** [ClementGre/PDF4Teachers#70]
I tried to rebuild with ./gradlew run

But I'm stopped by : 
```
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1071)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.util.MissingResourceException: Can't find bundle for base name translations/strings, locale en_US
        at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2048)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1682)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1575)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:930)
        at fr.clementgre.pdf4teachers@1.2.1/fr.clementgre.pdf4teachers.interfaces.windows.language.TR.getBundleByLocale(TR.java:55)
        at fr.clementgre.pdf4teachers@1.2.1/fr.clementgre.pdf4teachers.interfaces.windows.language.TR.setup(TR.java:39)
        at fr.clementgre.pdf4teachers@1.2.1/fr.clementgre.pdf4teachers.Main.start(Main.java:84)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        ... 1 more
Exception running application fr.clementgre.pdf4teachers.Main
:run (Thread[Execution worker for ':',5,main]) completed. Took 0.591 secs.
```
AFAIU, this is related to the missing translation resources (the README mentions "TranslationFileGenerator : used to generate the translations files using the code files. (Developped by me)."

It is a bit strange to rely on a tool that is to be installed before running gradlew run...

May I suggest to add more precise instructions on how to perform these steps before building, or some "rules" in gradle before the build and the run ?

Or maybe a git submodule that contains that TranslationFileGenerator tool, so as to run it from a subdir (a sub-checkout of its own repo), with a conf file already provided with the right paths ?

As such, it's a bit hard to rebuild the app, if one has to discover other tools, build, install and configure them, etc.

Hope this helps,

Best regards,

**Comment by olberger** [comment]
I've tried to install TranslationFileGenerator and change paths, but couldn't make the build work after having run it. Could youshare your config file ?

Or is this another kind of error, related to my gradle runtime configuration ?

**Comment by ClementGre** [comment]
Hey Olivier,

I'm sorry, I am actually editing the way the translations are working. In the future, there will be a key word for each translation instead of the French text which was used as a key until now.

You can checkout/reset to the last "stable" commit 02efbcb7bcc3ddc7640466c9d4bf35b638153dee.

TranslationFileGenerator don't have to be installed I just use it for generating the translations files (with the old system).

PS: You could see that it wont built with the badge on the top of the Readme [![Java CI with Gradle](https://github.com/clementgre/PDF4Teachers/workflows/build/badge.svg)](https://github.com/clementgre/PDF4Teachers/actions?query=workflow%3Abuild)  (Now it should work, with your pull request #69)

PS: My translations files should be names like en_US but I named them en_us so it could make some issues on Linux/Mac, which are os that take in account the case.

**Comment by olberger** [comment]
Thx for your feedback, of course, I was trying to build on master, and hadn't had a look at the recent commits, which give a clear indication of work in progress ;)

I'll let it up to you to close the issue, if you prefer to close it when you're done with the new system...

**Comment by ClementGre** [comment]
This error message ``Can't find bundle for base name translations/strings, locale en_US`` should impede you to build even with the #69 fix.
I think this issue is due to mac/linux where the case is taken in account. Are you on linux/mac ? (So I can be sure of that the issue is due to a case problem).

**Comment by ClementGre** [comment]
Anyway, the issue should be fixed now, I reviewed the way the ReaasourceBundle loader is working.
