### ISSUE TITLE
PDF4Teachers not starting

### ISSUE THREAD

**Issue by dgvincent** [ClementGre/PDF4Teachers#90]
- [X ] I checked the bug was not already reported [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+milestone%3A%22Release+1.2.1%22+-label%3A%22user+Issue%22+-label%3Aduplicate+-label%3Adocumentation+-label%3Aenhancement+-label%3A%22good+first+issue%22+-label%3A%22help+wanted%22+-label%3Aquestion)
- [X ] I checked the bug is not an existing user issue [here](https://github.com/clementgre/PDF4Teachers/issues?q=is%3Aissue+label%3A%22user+issue%22+)

**Describe the bug**
Application is not running on my mac with MacOs 13.1

**Check the console**
Starting PDF4Teachers...
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.HashMap (java.lang.String and java.util.HashMap are in module java.base of loader 'bootstrap')
	at fr.clementgre.pdf4teachers@1.2.1/fr.clementgre.pdf4teachers.datasaving.Config.load(Unknown Source)
	at fr.clementgre.pdf4teachers@1.2.1/fr.clementgre.pdf4teachers.datasaving.settings.Settings.loadSettings(Unknown Source)
	at fr.clementgre.pdf4teachers@1.2.1/fr.clementgre.pdf4teachers.datasaving.settings.Settings.<init>(Unknown Source)
	at fr.clementgre.pdf4teachers@1.2.1/fr.clementgre.pdf4teachers.Main.start(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
Exception running application fr.clementgre.pdf4teachers.Main
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Desktop (please complete the following information):**
 - OS+version: MacOs 13.1

**Comment by ClementGre** [comment]
Bonjour,

cette erreur est due à un problème de lecture du fichier paramètre de l'application. Vous pouvez le supprimer pour résoudre ce problème.
Il se situe dans ~/.PDF4Teachers/settings.yml

Vous pouvez aussi m'envoyer le fichier en question pour que je puisse mieux identifier le problème. Je vais essayer de régler ce problème pour la prochaine version.

Merci, Clément G.

**Comment by dgvincent** [comment]
Le voici !
